add module stats
AtamasMaria/java-explore-with-me pull request #3
Opened 2023-06-01 10:27 UTC by AtamasMaria

2023-06-03 19:33 UTC, ohelly approved these changes
Привет! Все супер, замечаний нет. Оставил несколько рекомендаций, на которые стоит обратить внимание. Работу принимаю, но есть вопрос, почему для клиента была выбрана зависимость webflux? Реактивное программирование довольно узкоспециализированное и зачастую будет лучше использовать тот же rest template или Feign

2023-06-03 19:33 UTC, ohelly commented on stats/stats-server/src/main/java/ru/practicum/server/controller/StatsController.java
> +    public void create(@RequestBody @Valid EndpointHitDto endpointHitDto) {
Рекомендация: Будет лучше если метод создания будет возвращать объект, который сохранил.

2023-06-03 19:33 UTC, ohelly commented on stats/stats-server/src/main/java/ru/practicum/server/controller/StatsController.java
> +        log.debug("Getting stats");
Рекомендация: В логи будет лучше добавить входные параметры

2023-06-03 19:33 UTC, ohelly commented on stats/stats-server/src/main/java/ru/practicum/server/model/ViewStats.java
> +public class ViewStats {
Рекомендация: Данный класс тоже можно сделать сущностью, а в БД создать не таблицу, а уже готовую вьюху
https://postgrespro.ru/docs/postgresql/9.6/sql-createview
Так будет удобнее писать SQL запросы

2023-06-03 19:33 UTC, ohelly commented on stats/stats-server/src/main/java/ru/practicum/server/service/StatsServiceImpl.java
> +    private List<ViewStatsDto> listToDto(List<ViewStats> list) {
Рекомендация: Данный метод можно вынести в маппер

2023-06-03 19:41 UTC, ohelly requested changes
Добавил одно замечание

2023-06-03 19:41 UTC, ohelly commented on stats/stats-client/src/main/java/ru/practicum/client/StatsClient.java
> +                .bodyToMono(ViewStatsDto.class)
Необходимо исправить: Если мы оджидаем, что вернется список, то мы должны использовать bodyToFlux, иначе сейчас вернется только один эелемент.
https://www.baeldung.com/java-reactor-flux-vs-mono

2023-06-04 04:27 UTC, AtamasMaria commented on stats/stats-server/src/main/java/ru/practicum/server/controller/StatsController.java
> +    public void create(@RequestBody @Valid EndpointHitDto endpointHitDto) {
Привет) Просто в ТЗ было написано, что можно использовать RestTemplate или WebClient я почитала, посмотрела пару видео и везде говорится, что RestTemplate устаревает и в целом его скоро заменит Клиент, поэтому решила попробовать, что это за зверь такой)

2023-06-04 04:28 UTC, AtamasMaria commented
Привет) Просто в ТЗ было написано, что можно использовать RestTemplate или WebClient я почитала, посмотрела пару видео и везде говорится, что RestTemplate устаревает и в целом его скоро заменит Клиент, поэтому решила попробовать, что это за зверь такой)

2023-06-04 05:04 UTC, AtamasMaria commented on stats/stats-server/src/main/java/ru/practicum/server/model/ViewStats.java
> +public class ViewStats {
Пока не совсем разобралась как правильно делать, боюсь ломать программу(, поэтому эту рекомендацию не выполнила

2023-06-04 15:02 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Можно двигаться дальше!

2023-06-05 16:32 UTC, merged